- type: job
  id: PirateFirstMate
  name: job-name-pirate-first-mate
  description: job-description-pirate-first-mate
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours # mono
    - !type:RoleTimeRequirement
      role: JobPDVDenasvar
      time: 28800 # 8 hours
  #whitelisted: true # mono - comment out
  startingGear: PirateFirstMateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateFirstMate"
  supervisors: job-supervisors-captain
  weight: 40
  displayWeight: 40
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  guides:
  - PDV_Entry
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateFirstMateNFGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility
    pocket1: BasePirateUplinkAsvaran
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
    - RubberStampPDVAsvaran # mono
