- type: job
  id: PirateCaptain
  name: job-name-pirate-captain
  description: job-description-pirate-captain
  playTimeTracker: JobPirateCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours # mono
    - !type:RoleTimeRequirement
      role: JobPDVDenasvar
      time: 28800 # 8 hours # mono
  enforcedPlayTime: true #Monolith
  whitelisted: true
  startingGear: PirateCaptainNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateCaptain"
  supervisors: job-supervisors-nobody
  weight: 50
  displayWeight: 50
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - GrandVizier
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  guides:
  - PDV_Entry
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
    - type: ChatRank
      rank: pdv-vizier
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateCaptainNFGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility # mono
    pocket1: BasePirateUplinkRadioPirateCaptain
    pocket2: EnergySword
  storage:
    back:
    - RadioHandheldNF # mono
    - PDVHandheldOverwatchConsole
    - RubberStampPDVVizier # mono
    - PhoneInstrumentHigh
    - WarDeclaratorPdv
