- type: job
  id: Pirate
  name: job-name-pirate
  description: job-description-pirate
  playTimeTracker: JobPirate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours. I don't expect new players to play almost 2 full rounds before they get bored, and it's mostly a raider check.
  startingGear: PirateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirate"
  supervisors: job-supervisors-pirate
  weight: 20
  displayWeight: 20
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - Mercenary
  accessGroups:
  - GeneralAccess
  guides:
  - PDV_Entry
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateNFGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    #belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
