- type: playTimeTracker
  id: JobUSSPCommissar

- type: playTimeTracker
  id: JobUSSPRifleman

- type: playTimeTracker
  id: JobUSSPSergeant

- type: playTimeTracker
  id: JobTsfEngineer

- type: playTimeTracker
  id: JobTsfCivilian

- type: playTimeTracker
  id: JobTsfBorg

- type: playTimeTracker
  id: JobPdvBorg

- type: playTimeTracker
  id: JobPdvCivilian

- type: playTimeTracker
  id: MdMedic

- type: playTimeTracker
  id: JobVGInfanteer

- type: playTimeTracker
  id: JobVGLieutenant

- type: playTimeTracker
  id: JobVGCommander

- type: playTimeTracker
  id: JobPDVTarkhan

- type: playTimeTracker
  id: JobTsfMarsoc

- type: playTimeTracker
  id: JobMMCEmployee

- type: playTimeTracker
  id: JobMMCSecurity

- type: playTimeTracker
  id: JobMMCLiason

#special adminbus roles
- type: playTimeTracker
  id: JobPDVAmbassador

- type: playTimeTracker
  id: JobPDVPrince

- type: playTimeTracker
  id: JobTSFInfantry

- type: playTimeTracker
  id: JobPDVInfantry

- type: playTimeTracker
  id: JobCrocusDockworker
