using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared._NSV.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NSV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class NsvSectorMonitorWindow : DefaultWindow
{
    // nodeId, faction
    public event Action<string, string>? OnSpawnFleet;
    // shipId, nodeId
    public event Action<string, string>? OnMoveFleet;
    // amount, absolute (set to amount instead of adding it)
    public event Action<int, bool>? OnAdjustScore;
    public event Action<float, bool>? OnAdjustThreat;

    // OptionButton item id -> faction id sent to the server.
    private static readonly string[] SpawnFactions = { "NSVHostile", "NSVFederal" };

    private NsvSectorMonitorNode[] _nodes = Array.Empty<NsvSectorMonitorNode>();
    private string _starmapId = string.Empty;
    private string? _selectedNodeId;
    private string? _selectedShipId;

    public NsvSectorMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        SetRows(Array.Empty<NsvSectorMonitorRow>());

        Tabs.SetTabTitle(0, Loc.GetString("nsv-sector-monitor-tab-campaign"));
        Tabs.SetTabTitle(1, Loc.GetString("nsv-sector-monitor-tab-sectors"));
        Tabs.SetTabTitle(2, Loc.GetString("nsv-sector-monitor-tab-starmap"));
        SetCampaign(null);

        ScoreMinus5.OnPressed += _ => OnAdjustScore?.Invoke(-5, false);
        ScoreMinus1.OnPressed += _ => OnAdjustScore?.Invoke(-1, false);
        ScorePlus1.OnPressed += _ => OnAdjustScore?.Invoke(1, false);
        ScorePlus5.OnPressed += _ => OnAdjustScore?.Invoke(5, false);
        ScoreSetButton.OnPressed += _ => SubmitScore();
        ScoreInput.OnTextEntered += _ => SubmitScore();
        ThreatMinus5.OnPressed += _ => OnAdjustThreat?.Invoke(-5f, false);
        ThreatMinus1.OnPressed += _ => OnAdjustThreat?.Invoke(-1f, false);
        ThreatPlus1.OnPressed += _ => OnAdjustThreat?.Invoke(1f, false);
        ThreatPlus5.OnPressed += _ => OnAdjustThreat?.Invoke(5f, false);
        ThreatSetButton.OnPressed += _ => SubmitThreat();
        ThreatInput.OnTextEntered += _ => SubmitThreat();

        FactionButton.AddItem(Loc.GetString("nsv-sector-monitor-spawn-faction-hostile"), 0);
        FactionButton.AddItem(Loc.GetString("nsv-sector-monitor-spawn-faction-federal"), 1);
        FactionButton.OnItemSelected += args => FactionButton.SelectId(args.Id);
        FactionButton.SelectId(0);

        Starmap.OnNodeSelected += OnNodeSelected;
        FleetList.OnItemSelected += OnFleetSelected;
        FleetList.OnItemDeselected += _ => { _selectedShipId = null; UpdateMoveState(); };
        SpawnFleetButton.OnPressed += _ =>
        {
            if (_selectedNodeId != null)
                OnSpawnFleet?.Invoke(_selectedNodeId, SpawnFactions[FactionButton.SelectedId]);
        };
        MoveFleetButton.OnPressed += _ =>
        {
            if (_selectedShipId != null && _selectedNodeId != null)
                OnMoveFleet?.Invoke(_selectedShipId, _selectedNodeId);
        };
    }

    public void SetState(NsvSectorMonitorEuiState state)
    {
        SetCapacityLabel(
            TotalSectorCapacity,
            "nsv-sector-monitor-total-capacity",
            state.TotalSectorCount,
            state.TotalSectorSoftCapacity);
        SetCapacityLabel(
            ActiveSectorCapacity,
            "nsv-sector-monitor-active-capacity",
            state.ActiveSectorCount,
            state.ActiveSectorSoftCapacity);
        SetRows(state.Rows);
        SetCampaign(state.Campaign);
        StatusLabel.Text = state.StatusMessage ?? string.Empty;

        _nodes = state.Nodes;
        _starmapId = state.StarmapId;
        Starmap.SetNodes(state.Nodes);
        Starmap.SetSelected(_selectedNodeId);

        SetFleets(state.Fleets);
        RefreshSelectedNode();
        UpdateMoveState();
    }

    private void SetCampaign(NsvSectorMonitorCampaign? campaign)
    {
        NoCampaignLabel.Visible = campaign == null;
        CampaignContent.Visible = campaign != null;
        foreach (var button in new[] { BriefingButton, ReminderButton, BlockadeButton, StartVoteButton })
            button.Disabled = campaign == null;

        ObjectivesContainer.RemoveAllChildren();
        if (campaign == null)
            return;

        var summary = campaign.Summary;
        PhaseValue.Text = Loc.GetString(summary.PhaseLoc);
        OutcomeValue.Text = campaign.Outcome;
        ScoreValue.Text = summary.Score.ToString();
        ThreatValue.Text = summary.ThreatElevation.ToString();
        ActiveTimeValue.Text = FormatSeconds(campaign.ActiveSeconds);
        BriefingValue.Text = Loc.GetString(campaign.BriefingDelivered
            ? "nsv-sector-monitor-campaign-briefing-sent"
            : "nsv-sector-monitor-campaign-briefing-pending");
        ReminderStageValue.Text = Loc.GetString("nsv-sector-monitor-campaign-reminder-stage-value",
            ("stage", campaign.ReminderStage));
        NextReminderValue.Text = campaign.NextReminderSeconds is { } next
            ? FormatSeconds(next)
            : Loc.GetString("nsv-sector-monitor-campaign-reminder-paused");
        ExtensionValue.Text = campaign.ExtensionSeconds is { } extension ? FormatSeconds(extension) : "-";

        foreach (var objective in summary.Objectives)
        {
            ObjectivesContainer.AddChild(new Label
            {
                Text = Loc.GetString("nsv-sector-monitor-campaign-objective",
                    ("label", Loc.GetString(objective.LabelLoc)),
                    ("status", Loc.GetString(objective.StatusLoc)),
                    ("tally", objective.Tally),
                    ("target", objective.Target)),
            });
        }
    }

    private void SubmitScore()
    {
        if (int.TryParse(ScoreInput.Text, out var score))
            OnAdjustScore?.Invoke(score, true);
    }

    private void SubmitThreat()
    {
        if (float.TryParse(ThreatInput.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var threat))
        {
            OnAdjustThreat?.Invoke(threat, true);
        }
    }

    private static string FormatSeconds(int seconds)
    {
        return TimeSpan.FromSeconds(Math.Max(0, seconds)).ToString(seconds >= 3600 ? @"h\:mm\:ss" : @"mm\:ss");
    }

    private void SetFleets(NsvSectorMonitorFleet[] fleets)
    {
        FleetList.Clear();
        foreach (var fleet in fleets)
        {
            var node = fleet.NodeId ?? "-";
            var label = Loc.GetString(
                "nsv-sector-monitor-fleet-entry",
                ("id", fleet.ShipId),
                ("state", fleet.State),
                ("faction", fleet.Faction ?? "-"),
                ("node", node),
                ("completeness", (int) MathF.Round(fleet.Completeness * 100)));
            var item = FleetList.AddItem(label);
            item.Metadata = fleet.ShipId;
            if (fleet.ShipId == _selectedShipId)
                item.Selected = true;
        }

        if (_selectedShipId != null && fleets.All(f => f.ShipId != _selectedShipId))
            _selectedShipId = null;
    }

    private void OnNodeSelected(string nodeId)
    {
        _selectedNodeId = nodeId;
        RefreshSelectedNode();
        UpdateMoveState();
    }

    private void OnFleetSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedShipId = FleetList[args.ItemIndex].Metadata as string;
        UpdateMoveState();
    }

    private void RefreshSelectedNode()
    {
        var node = _selectedNodeId == null
            ? null
            : _nodes.FirstOrDefault(n => n.Id == _selectedNodeId);

        ResidentList.Clear();

        if (node == null)
        {
            SelectedNodeLabel.Text = Loc.GetString("nsv-sector-monitor-node-none");
            SpawnFleetButton.Disabled = true;
            return;
        }

        var stateText = node.HasSector && node.SectorState != null
            ? LocalizeState(node.SectorState)
            : Loc.GetString("nsv-sector-monitor-node-data-only");
        SelectedNodeLabel.Text = Loc.GetString(
            "nsv-sector-monitor-node-selected",
            ("id", node.Id),
            ("state", stateText));

        foreach (var shipId in node.ResidentShipIds)
            ResidentList.AddItem(shipId);

        SpawnFleetButton.Disabled = false;
    }

    private void UpdateMoveState()
    {
        MoveFleetButton.Disabled = _selectedShipId == null || _selectedNodeId == null;
        MoveTargetLabel.Text = _selectedShipId != null && _selectedNodeId != null
            ? Loc.GetString("nsv-sector-monitor-move-target", ("ship", _selectedShipId), ("node", _selectedNodeId))
            : Loc.GetString("nsv-sector-monitor-move-target-none");
    }

    public string StarmapId => _starmapId;

    public void SetRows(IReadOnlyList<NsvSectorMonitorRow> rows)
    {
        Rows.RemoveAllChildren();
        AddHeader("nsv-sector-monitor-column-name", 180);
        AddHeader("nsv-sector-monitor-column-id", 150);
        AddHeader("nsv-sector-monitor-column-state", 130);
        AddHeader("nsv-sector-monitor-column-owned-grids", 110);
        AddHeader("nsv-sector-monitor-column-owned-entities", 120);
        AddHeader("nsv-sector-monitor-column-foreign-grids", 110);
        AddHeader("nsv-sector-monitor-column-pending-arrivals", 130);
        AddHeader("nsv-sector-monitor-column-must-run-blockers", 130);
        AddHeader("nsv-sector-monitor-column-sleep-hold", 120);

        foreach (var row in rows)
        {
            var name = row.NameFallback;
            if (!string.IsNullOrEmpty(row.NameLocId) && Loc.TryGetString(row.NameLocId, out var localizedName))
                name = localizedName;

            AddCell(name, 180);
            AddCell(row.Id, 150);
            AddCell(LocalizeState(row.State), 130);
            AddCell(row.OwnedGrids.ToString(), 110);
            AddCell(row.OwnedEntities.ToString(), 120);
            AddCell(row.ForeignGrids.ToString(), 110);
            AddCell(row.PendingArrivals.ToString(), 130);
            AddCell(row.MustRunTaskBlockers.ToString(), 130);
            AddCell(row.SleepHoldSeconds?.ToString() ?? "-", 120);
        }
    }

    private static void SetCapacityLabel(Label label, string locId, int count, int maximum)
    {
        label.Text = Loc.GetString(locId, ("count", count), ("maximum", maximum));
        label.FontColorOverride = count > maximum ? StyleNano.ConcerningOrangeFore : null;
    }

    private void AddHeader(string locId, float width)
    {
        var label = AddCell(Loc.GetString(locId), width);
        label.AddStyleClass(StyleBase.StyleClassLabelHeading);
    }

    private Label AddCell(string text, float width)
    {
        var label = new Label
        {
            Text = text,
            MinWidth = width,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };
        Rows.AddChild(label);
        return label;
    }

    private static string LocalizeState(string state)
    {
        var locId = state switch
        {
            "Applying" => "nsv-bluespace-console-sector-status-applying",
            "Ready" => "nsv-bluespace-console-sector-status-ready",
            "PreparingSleep" => "nsv-bluespace-console-sector-status-preparing-sleep",
            "Sleeping" => "nsv-bluespace-console-sector-status-sleeping",
            "Waking" => "nsv-bluespace-console-sector-status-waking",
            "Draining" => "nsv-bluespace-console-sector-status-draining",
            "Failed" => "nsv-bluespace-console-sector-status-failed",
            _ => null,
        };

        return locId == null ? state : Loc.GetString(locId);
    }
}
