using Content.Client.Stylesheets;
using Content.Shared._NSV.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NSV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class NsvSectorMonitorWindow : DefaultWindow
{
    public NsvSectorMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        SetRows(Array.Empty<NsvSectorMonitorRow>());
    }

    public void SetRows(IReadOnlyList<NsvSectorMonitorRow> rows)
    {
        Rows.RemoveAllChildren();
        AddHeader("nsv-sector-monitor-column-name", 180);
        AddHeader("nsv-sector-monitor-column-id", 150);
        AddHeader("nsv-sector-monitor-column-state", 130);
        AddHeader("nsv-sector-monitor-column-owned-grids", 110);
        AddHeader("nsv-sector-monitor-column-owned-entities", 120);
        AddHeader("nsv-sector-monitor-column-foreign-grids", 110);
        AddHeader("nsv-sector-monitor-column-pending-arrivals", 130);

        foreach (var row in rows)
        {
            var name = row.NameFallback;
            if (!string.IsNullOrEmpty(row.NameLocId) && Loc.TryGetString(row.NameLocId, out var localizedName))
                name = localizedName;

            AddCell(name, 180);
            AddCell(row.Id, 150);
            AddCell(LocalizeState(row.State), 130);
            AddCell(row.OwnedGrids.ToString(), 110);
            AddCell(row.OwnedEntities.ToString(), 120);
            AddCell(row.ForeignGrids.ToString(), 110);
            AddCell(row.PendingArrivals.ToString(), 130);
        }
    }

    private void AddHeader(string locId, float width)
    {
        var label = AddCell(Loc.GetString(locId), width);
        label.AddStyleClass(StyleBase.StyleClassLabelHeading);
    }

    private Label AddCell(string text, float width)
    {
        var label = new Label
        {
            Text = text,
            MinWidth = width,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };
        Rows.AddChild(label);
        return label;
    }

    private static string LocalizeState(string state)
    {
        var locId = state switch
        {
            "Applying" => "nsv-bluespace-console-sector-status-applying",
            "Ready" => "nsv-bluespace-console-sector-status-ready",
            "PreparingSleep" => "nsv-bluespace-console-sector-status-preparing-sleep",
            "Sleeping" => "nsv-bluespace-console-sector-status-sleeping",
            "Draining" => "nsv-bluespace-console-sector-status-draining",
            "Failed" => "nsv-bluespace-console-sector-status-failed",
            _ => null,
        };

        return locId == null ? state : Loc.GetString(locId);
    }
}
