- type: job
  id: SecurityGuard
  name: job-name-security-guard
  description: job-description-security-guard
  playTimeTracker: JobSecurityGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours. I don't expect new players to play almost 2 full rounds before they get bored, and it's mostly a raider check.
  startingGear: SecurityGuardGear
  alwaysUseSpawner: true
  icon: "JobIconSecurityGuard"
  supervisors: job-supervisors-sr
  assignedCompany: Colonial
  weight: 80
  displayWeight: 20 # Second from the bottom
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary
  - Captain
  - Frontier
  guides:
  - Caelestinus
  special:
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: cc-judge
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Mono - remove TSFMC implant
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SecurityGuardGear
  equipment:
    pocket1: WeaponEnergyGunLawbringer
  storage:
    back:
    - EncryptionKeyService
    - EncryptionKeySecurity
    - ShipVoucherFrontierGuard
