using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NSV.Cargo;

[GenerateTypedNameReferences]
public sealed partial class NsvCargoSellConsoleWindow : FancyWindow
{
    public event Action? SellRequested;
    public event Action? AppraiseRequested;

    public NsvCargoSellConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        AppraiseButton.OnPressed += _ => AppraiseRequested?.Invoke();
        SellButton.OnPressed += _ => SellRequested?.Invoke();
    }

    public void UpdateState(int balance, int appraisal, int count, string marketName, bool enabled)
    {
        MarketLabel.Text = string.IsNullOrEmpty(marketName)
            ? Loc.GetString("nsv-cargo-sell-market-none")
            : marketName;
        BalanceLabel.Text = balance.ToString();
        AppraisalLabel.Text = count > 0
            ? appraisal.ToString()
            : Loc.GetString("nsv-cargo-sell-no-goods-text");
        CountLabel.Text = count > 0
            ? count.ToString()
            : Loc.GetString("nsv-cargo-sell-no-goods-text");
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled || count <= 0;
    }
}
