using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.PDV.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mono.PDV.UI;

[GenerateTypedNameReferences]
public sealed partial class HereticMenu : FancyWindow
{
    public HereticMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateEntries(List<Heretic> heretics)
    {
        HereticEntriesContainer.Children.Clear();
        foreach (var h in heretics)
        {
            var entry = new HereticEntry(h);

            HereticEntriesContainer.AddChild(entry);
        }
        HereticEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });
    }
}
