using Content.Client.Message;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared._Mono.PDV.Components;

namespace Content.Client._Mono.PDV.UI;

[GenerateTypedNameReferences]
public sealed partial class HereticEntry : BoxContainer
{
    public HereticEntry(Heretic heretic)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var items = new List<string>();

        var reward = heretic.Reward;
        items.Add(Loc.GetString("pdv-heretic-console-entry",
            ("item", heretic.Name)));
        ManifestLabel.SetMarkup(Loc.GetString("pirate-bounty-console-manifest-label", ("item", string.Join(", ", items))));
        RewardLabel.SetMarkup(Loc.GetString("pirate-bounty-console-reward-label", ("reward", reward)));
        DescriptionLabel.SetMarkup(Loc.GetString("pdv-heretic-console-description"));
    }
}
