- type: entity
  name: base economy item
  description: Used to keeo the ol' rust belt rolling.
  parent: BaseItem
  id: BaseEconomyGood
  abstract: true
  components:
  - type: Tag
    tags:
    - EconomyGood
  - type: Item
    size: Normal
  - type: Sprite
    sprite: _Mono/Objects/Materials/bayponents.rsi
    state: "armor1"
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 200
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalBreak
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
# Cherry picked base item things
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_Goobstation/Items/handling/phone_pickup.ogg
      params:
        volume: -2
  - type: EmitSoundOnDrop
    sound:
      path: /Audio/_Goobstation/Items/handling/phone_drop.ogg
      params:
        volume: -2
  - type: Animateable
  - type: Clickable
  - type: InteractionOutline
  - type: MovedByPressure
  - type: EmitSoundOnCollide
    sound:
      collection: WeakHit
  - type: EmitSoundOnLand
    sound:
      path: /Audio/Effects/drop.ogg
      params:
        volume: 2
  - type: Physics
    bodyType: Dynamic
    fixedRotation: false
  - type: Pullable
  - type: DamageExaminable
  - type: GuideHelp
    guides:
    - Economy
  - type: StaticPrice
    price: 300

- type: entity
  name: base economy item
  description: Used to keeo the ol' rust belt rolling.
  parent: BaseEconomyGood
  id: BaseEconomyGoodTier1
  abstract: true
  suffix: T1

- type: entity
  name: base economy item
  description: Used to keeo the ol' rust belt rolling.
  parent: BaseEconomyGood
  id: BaseEconomyGoodTier2
  abstract: true
  suffix: T2

- type: entity
  name: base economy item
  description: Used to keeo the ol' rust belt rolling.
  parent: BaseEconomyGood
  id: BaseEconomyGoodTier3
  abstract: true
  suffix: T3

- type: entity
  name: base economy item
  description: Used to keeo the ol' rust belt rolling.
  parent: BaseEconomyGood
  id: BaseEconomyGoodTier4
  abstract: true
  suffix: T4
