using Content.Shared._NSV.Bluespace.Sectors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._NSV.Bluespace.Sectors;

[GenerateTypedNameReferences]
public sealed partial class NsvBluespaceNavigationCartridgeUiFragment : BoxContainer
{
    public NsvBluespaceNavigationCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        UpdateState(new NsvBluespaceCartridgeUiState(
            false,
            "nsv-bluespace-cartridge-no-sector",
            "nsv-bluespace-console-sector-status-awaiting-jump",
            null,
            null,
            false,
            null,
            null,
            null,
            0,
            false,
            false));
    }

    public void UpdateState(NsvBluespaceCartridgeUiState state)
    {
        SectorNameValue.Text = Loc.GetString(state.SectorName);
        SectorStatusValue.Text = Loc.GetString(state.SectorStatus);
        SectorAssetsValue.Text = state.OwnedGridCount is { } grids && state.OwnedEntityCount is { } entities
            ? Loc.GetString("nsv-bluespace-console-sector-assets-value", ("grids", grids), ("entities", entities))
            : "—";

        if (!state.HasEncounter)
        {
            EncounterNameValue.Text = Loc.GetString("nsv-bluespace-console-encounter-none");
            EncounterObjectiveValue.Text = "—";
            EncounterStatusValue.Text = "—";
            EncounterParticipantsValue.Text = "—";
            EncounterRoleValue.Text = "—";
            EncounterExtractionValue.Text = "—";
            return;
        }

        EncounterNameValue.Text = Loc.GetString(state.EncounterName!);
        EncounterObjectiveValue.Text = Loc.GetString(state.EncounterObjective!);
        EncounterStatusValue.Text = Loc.GetString(state.EncounterStatus!);
        EncounterParticipantsValue.Text = state.ParticipantCount.ToString();
        EncounterRoleValue.Text = Loc.GetString(state.IsParticipant
            ? "nsv-bluespace-console-encounter-participant"
            : "nsv-bluespace-console-encounter-observer");
        EncounterExtractionValue.Text = Loc.GetString(state.CanExtract
            ? "nsv-bluespace-console-extraction-open"
            : "nsv-bluespace-console-extraction-locked");
    }
}
