using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NSV.Bluespace.Sectors;
using Content.Shared._NSV.Bluespace.Starmap;
using Content.Shared.Input;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._NSV.Bluespace.Sectors;

[UsedImplicitly]
public sealed class NsvBluespaceNavigationConsoleBoundUserInterface(EntityUid owner, Enum uiKey) : BoundUserInterface(owner, uiKey)
{
    private NsvBluespaceNavigationConsoleWindow? _window;
    private NsvBluespaceNavigationConsoleState? _state;

    protected override void Open()
    {
        base.Open();
        _window = this.CreateWindow<NsvBluespaceNavigationConsoleWindow>();
        _window.RequestTravel += (destinationNodeId, returnToDeparture) =>
            SendMessage(new NsvBluespaceJumpRequestMessage(destinationNodeId, returnToDeparture));
        if (_state != null)
            _window.UpdateState(_state);
    }

    protected override void UpdateState(BoundUserInterfaceState state)
    {
        base.UpdateState(state);
        if (state is not NsvBluespaceNavigationConsoleState navigationState)
            return;

        _state = navigationState;
        _window?.UpdateState(navigationState);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _window?.Dispose();
    }
}

[GenerateTypedNameReferences]
public sealed partial class NsvBluespaceNavigationConsoleWindow : FancyWindow
{
    private NsvBluespaceNavigationConsoleState? _state;
    private string? _selectedNodeId;

    public event Action<string?, bool>? RequestTravel;

    public NsvBluespaceNavigationConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        var group = new ButtonGroup();
        SectorModeButton.Group = group;
        EncounterModeButton.Group = group;
        StarmapModeButton.Group = group;
        SectorModeButton.Pressed = true;

        SectorModeButton.OnPressed += _ => SwitchMode(NsvBluespaceConsoleMode.Sector);
        EncounterModeButton.OnPressed += _ => SwitchMode(NsvBluespaceConsoleMode.Encounter);
        StarmapModeButton.OnPressed += _ => SwitchMode(NsvBluespaceConsoleMode.Starmap);

        StarmapControl.NodeSelected += SelectNode;
        JumpButton.OnPressed += _ => RequestTravel?.Invoke(_selectedNodeId, false);
        ReturnButton.OnPressed += _ => RequestTravel?.Invoke(null, true);
    }

    private void SwitchMode(NsvBluespaceConsoleMode mode)
    {
        SectorScreen.Visible = mode == NsvBluespaceConsoleMode.Sector;
        EncounterScreen.Visible = mode == NsvBluespaceConsoleMode.Encounter;
        StarmapScreen.Visible = mode == NsvBluespaceConsoleMode.Starmap;
    }

    public void UpdateState(NsvBluespaceNavigationConsoleState state)
    {
        _state = state;
        SectorNameValue.Text = Loc.GetString(state.SectorName);
        SectorStatusValue.Text = Loc.GetString(state.SectorStatus);
        SectorAssetsValue.Text = state.OwnedGridCount is { } grids && state.OwnedEntityCount is { } entities
            ? Loc.GetString("nsv-bluespace-console-sector-assets-value", ("grids", grids), ("entities", entities))
            : "—";
        SectorDescriptionValue.Text = Loc.GetString(state.SectorDescription);

        if (!state.HasEncounter)
        {
            EncounterNameValue.Text = Loc.GetString("nsv-bluespace-console-encounter-none");
            EncounterObjectiveValue.Text = "—";
            EncounterStatusValue.Text = "—";
            EncounterParticipantsValue.Text = "—";
            EncounterRoleValue.Text = "—";
            EncounterExtractionValue.Text = "—";
        }
        else
        {
            EncounterNameValue.Text = Loc.GetString(state.EncounterName!);
            EncounterObjectiveValue.Text = Loc.GetString(state.EncounterObjective!);
            EncounterStatusValue.Text = Loc.GetString(state.EncounterStatus!);
            EncounterParticipantsValue.Text = state.ParticipantCount.ToString();
            EncounterRoleValue.Text = Loc.GetString(state.IsParticipant
                ? "nsv-bluespace-console-encounter-participant"
                : "nsv-bluespace-console-encounter-observer");
            EncounterExtractionValue.Text = Loc.GetString(state.CanExtract
                ? "nsv-bluespace-console-extraction-open"
                : "nsv-bluespace-console-extraction-locked");
        }

        StarmapControl.SetNodes(state.StarmapNodes, _selectedNodeId);
        if (_selectedNodeId != null && state.StarmapNodes.All(node => node.Id != _selectedNodeId))
            _selectedNodeId = null;

        UpdateSelectedNode();
        ReturnButton.Disabled = !state.CanReturnToDeparture;
    }

    private void SelectNode(string nodeId)
    {
        _selectedNodeId = nodeId;
        StarmapControl.SetSelectedNode(nodeId);
        UpdateSelectedNode();
    }

    private void UpdateSelectedNode()
    {
        var node = _state?.StarmapNodes.FirstOrDefault(candidate => candidate.Id == _selectedNodeId);
        if (node == null)
        {
            SelectedNodeNameValue.Text = Loc.GetString("nsv-bluespace-console-starmap-no-selection");
            SelectedNodeTypeValue.Text = "—";
            SelectedNodeThreatValue.Text = "—";
            SelectedNodeRewardValue.Text = "—";
            SelectedNodeFuelValue.Text = "—";
            SelectedNodeFactionValue.Text = "—";
            SelectedNodeEncountersValue.Text = "—";
            SelectedNodeDescriptionValue.Text = string.Empty;
            JumpButton.Disabled = true;
            return;
        }

        SelectedNodeNameValue.Text = Loc.GetString(node.Name);
        SelectedNodeTypeValue.Text = Loc.GetString(GetNodeTypeKey(node.Type));
        SelectedNodeThreatValue.Text = node.Threat.ToString();
        SelectedNodeRewardValue.Text = node.Reward.ToString();
        SelectedNodeFuelValue.Text = node.FuelCost.ToString();
        SelectedNodeFactionValue.Text = node.Faction;
        SelectedNodeEncountersValue.Text = node.EncounterNames.Count.ToString();
        SelectedNodeDescriptionValue.Text = Loc.GetString(node.Description);
        JumpButton.Disabled = !node.IsSelectable;
    }

    private static string GetNodeTypeKey(NsvBluespaceStarmapNodeType type)
    {
        return type switch
        {
            NsvBluespaceStarmapNodeType.Home => "nsv-bluespace-console-starmap-node-home",
            NsvBluespaceStarmapNodeType.Asteroid => "nsv-bluespace-console-starmap-node-asteroid",
            NsvBluespaceStarmapNodeType.Distress => "nsv-bluespace-console-starmap-node-distress",
            NsvBluespaceStarmapNodeType.PiratePatrol => "nsv-bluespace-console-starmap-node-pirate-patrol",
            NsvBluespaceStarmapNodeType.UnknownSignal => "nsv-bluespace-console-starmap-node-unknown-signal",
            _ => "nsv-bluespace-console-starmap-node-unknown-signal"
        };
    }

    public enum NsvBluespaceConsoleMode : byte
    {
        Sector,
        Encounter,
        Starmap,
    }
}

public sealed class NsvBluespaceStarmapControl : Control
{
    private const float Padding = 20f;
    private const float NodeRadius = 9f;
    private readonly Dictionary<string, NsvBluespaceStarmapNodeState> _nodes = new(StringComparer.Ordinal);
    private string? _selectedNodeId;

    public event Action<string>? NodeSelected;

    public NsvBluespaceStarmapControl()
    {
        MouseFilter = MouseFilterMode.Stop;
    }

    public void SetNodes(IEnumerable<NsvBluespaceStarmapNodeState> nodes, string? selectedNodeId)
    {
        _nodes.Clear();
        foreach (var node in nodes)
            _nodes[node.Id] = node;

        _selectedNodeId = selectedNodeId;
    }

    public void SetSelectedNode(string? selectedNodeId)
    {
        _selectedNodeId = selectedNodeId;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        foreach (var node in _nodes.Values)
        {
            if (Vector2.DistanceSquared(args.RelativePosition * UIScale, ToLocalPosition(node.Position)) > NodeRadius * NodeRadius * 4f)
                continue;

            NodeSelected?.Invoke(node.Id);
            return;
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        if (_nodes.Count == 0)
            return;

        var bounds = new UIBox2(Vector2.Zero, new Vector2(PixelWidth, PixelHeight));
        handle.DrawRect(bounds, new Color(24, 30, 40));

        foreach (var node in _nodes.Values)
        {
            foreach (var linkedId in node.Connections)
            {
                if (string.CompareOrdinal(node.Id, linkedId) >= 0 || !_nodes.TryGetValue(linkedId, out var linked))
                    continue;

                handle.DrawLine(ToLocalPosition(node.Position), ToLocalPosition(linked.Position), new Color(104, 116, 135));
            }
        }

        foreach (var node in _nodes.Values)
        {
            var color = node.Id == _selectedNodeId
                ? new Color(255, 210, 82)
                : node.IsCurrent
                    ? new Color(71, 203, 127)
                    : node.IsSelectable
                        ? new Color(93, 173, 226)
                        : new Color(123, 133, 145);
            handle.DrawCircle(ToLocalPosition(node.Position), NodeRadius, color);
        }
    }

    private Vector2 ToLocalPosition(Vector2 position)
    {
        var min = new Vector2(float.PositiveInfinity, float.PositiveInfinity);
        var max = new Vector2(float.NegativeInfinity, float.NegativeInfinity);
        foreach (var node in _nodes.Values)
        {
            min = Vector2.Min(min, node.Position);
            max = Vector2.Max(max, node.Position);
        }

        var range = Vector2.Max(max - min, Vector2.One);
        var available = new Vector2(MathF.Max(1f, PixelWidth - Padding * 2f), MathF.Max(1f, PixelHeight - Padding * 2f));
        var normalized = new Vector2((position.X - min.X) / range.X, 1f - (position.Y - min.Y) / range.Y);
        return new Vector2(Padding, Padding) + normalized * available;
    }
}
