- type: job
  id: Sheriff
  name: job-name-sheriff
  description: job-description-sheriff
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 10800 # 3 hours
  enforcedPlayTime: true #Monolith
  whitelisted: true
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 180
  displayWeight: 70
  assignedCompany: TSF
  canBeAntag: false
  accessGroups:
  - AllAccessMono #Mono Start
  access:
  - TsfmcEngineering
  - HeadOfSecurity
  - Bailiff
  - Sergeant
  - Armory
  - Frontier #Mono End
  guides:
  - TSFMC_Entry
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SheriffGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - PhoneInstrumentHigh
    - RubberStampTSFColonel #Mono. Look, it had comments on the Bailiff/Captain file.
    - TSFHandheldOverwatchConsole
    - BookTSFSOP
    - WarDeclaratorTsf
